export const messageUtil = {
  OK: 'OK',
  EMPTY_FIELD: 'Please Enter feilds are required.',
  ALL_READY_EXIST: 'Record Already Exist',
  USER_CREATED: 'User Created Successfully',
  Gig_CREATED: 'Gig Created Successfully',
  Package_CREATED: 'Package Created Successfully',
  RECORD_NOT_CREATED: 'Record Not Created',
  NOT_FOUND: 'Record Not Found',
  LOGIN_SUCCESS: 'Login Successfully',
  UNAUTHORIZED: 'User not authorized',
  FIELDS_REQUIRED: 'All fields (username, email, and password) are required.',
  INVALID_VERIFICATION_CODE: 'Invalid verification code.',
  INVALID_OR_EXPIRE_TOKEN: 'Invalid or Expire ResetToken.',
  VERIFIED: 'Email verified successfully.',
  NOT_VERIFIED: 'Email NOT verified.',
  INCORRECT_PASSWORD: 'Incorrect Password',
  Email_BOX: 'Please check your Email Box',
  INVALID_CODE_EXPIRE_CODE: 'Invalid or expire code',
  PASSWORD_RESET: 'Password Reset successfully.',
  USER_UPDATED: 'User Updated Successfully',
  Gig_UPDATED: 'Gig Updated Successfully',
  Package_UPDATED: 'Package Updated Successfully',
  PROFILE_UPDATED: 'Profile Updated Successfully',
  CURRENT_USER: 'Current User Not Set',
  DELETE_RECORD: 'Record Deleted Successfully',
  RECORD_UPDATED: 'Record Updated Successfully',
  USER_DELETE: 'User Deleted Successfully',
  GIG_DELETE: 'Gig Deleted Successfully',
  Package_DELETE: 'Package Deleted Successfully',
  PROFILE_DELETE: 'Profile Deleted Successfully',
  NO_UPLOAD_FILE: 'File upload failed, no file received',
  PAYMENT_ERROR: 'Payment error',
  serverError: 'Server Error',
};
